name: zippy
description: "A package to intgrate zippy form"
version: 0.0.1
repository: https://github.com/aravind-m-s

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  multi_dropdown: ^3.0.1
  skeletonizer: ^1.4.2
  
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

